name: dart_bolt
description: A Dart library for Bolt protocol implementation.
version: 1.0.0
resolution: workspace
repository: https://github.com/exaby73/dart_neo4j/tree/main/packages/dart_bolt

environment:
  sdk: ^3.8.0

dependencies:
  dart_packstream: ^0.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
