services:
  # Single Neo4j instance for bolt:// testing
  neo4j-single:
    image: neo4j:2025.05-enterprise
    container_name: neo4j-single
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
    volumes:
      - neo4j-single-data:/data
      - neo4j-single-logs:/logs
    networks:
      - neo4j-network

  # Neo4j Cluster for neo4j:// routing testing
  neo4j-core1:
    image: neo4j:2025.05-enterprise
    container_name: neo4j-core1
    ports:
      - 7475:7474
      - 7688:7687
      - 7689:7688
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_dbms_cluster_minimum__initial__system__primaries__count=3
      - NEO4J_internal_db_cluster_raft_minimum__voting__members=3
      - NEO4J_server_bolt_listen__address=0.0.0.0:7687
      - NEO4J_server_http_listen__address=0.0.0.0:7474
      - NEO4J_dbms_routing_default__router=SERVER
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
    volumes:
      - neo4j-core1-data:/data
      - neo4j-core1-logs:/logs
    networks:
      - neo4j-network

  neo4j-core2:
    image: neo4j:2025.05-enterprise
    container_name: neo4j-core2
    ports:
      - 7476:7474
      - 7690:7687
      - 7691:7688
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_dbms_cluster_minimum__initial__system__primaries__count=3
      - NEO4J_internal_db_cluster_raft_minimum__voting__members=3
      - NEO4J_server_bolt_listen__address=0.0.0.0:7687
      - NEO4J_server_http_listen__address=0.0.0.0:7474
      - NEO4J_dbms_routing_default__router=SERVER
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
    volumes:
      - neo4j-core2-data:/data
      - neo4j-core2-logs:/logs
    networks:
      - neo4j-network

  neo4j-core3:
    image: neo4j:2025.05-enterprise
    container_name: neo4j-core3
    ports:
      - 7477:7474
      - 7692:7687
      - 7693:7688
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_dbms_cluster_minimum__initial__system__primaries__count=3
      - NEO4J_internal_db_cluster_raft_minimum__voting__members=3
      - NEO4J_server_bolt_listen__address=0.0.0.0:7687
      - NEO4J_server_http_listen__address=0.0.0.0:7474
      - NEO4J_dbms_routing_default__router=SERVER
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
    volumes:
      - neo4j-core3-data:/data
      - neo4j-core3-logs:/logs
    networks:
      - neo4j-network

  # SSL-enabled single Neo4j instance for bolt+s:// testing
  neo4j-single-ssl:
    image: neo4j:2025.05-enterprise
    container_name: neo4j-single-ssl
    ports:
      - 7478:7474
      - 7694:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
      # SSL Configuration
      - NEO4J_server_bolt_tls__level=REQUIRED
      - NEO4J_dbms_ssl_policy_bolt_enabled=true
      - NEO4J_dbms_ssl_policy_bolt_base__directory=/var/lib/neo4j/certificates/bolt
      - NEO4J_dbms_ssl_policy_bolt_private__key=server-key.pem
      - NEO4J_dbms_ssl_policy_bolt_public__certificate=server-cert.pem
      - NEO4J_dbms_ssl_policy_bolt_client__auth=NONE
    volumes:
      - neo4j-single-ssl-data:/data
      - neo4j-single-ssl-logs:/logs
      - ./ssl-certs:/var/lib/neo4j/certificates/bolt
    networks:
      - neo4j-network

  # Self-signed SSL Neo4j instance for bolt+ssc:// testing
  neo4j-self-signed:
    image: neo4j:2025.05-enterprise
    container_name: neo4j-self-signed
    ports:
      - 7479:7474
      - 7695:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
      # Self-signed SSL Configuration
      - NEO4J_server_bolt_tls__level=REQUIRED
      - NEO4J_dbms_ssl_policy_bolt_enabled=true
      - NEO4J_dbms_ssl_policy_bolt_base__directory=/var/lib/neo4j/certificates/bolt
      - NEO4J_dbms_ssl_policy_bolt_private__key=server-key.pem
      - NEO4J_dbms_ssl_policy_bolt_public__certificate=self-signed-cert.pem
      - NEO4J_dbms_ssl_policy_bolt_client__auth=NONE
    volumes:
      - neo4j-self-signed-data:/data
      - neo4j-self-signed-logs:/logs
      - ./ssl-certs:/var/lib/neo4j/certificates/bolt
    networks:
      - neo4j-network


volumes:
  neo4j-single-data:
  neo4j-single-logs:
  neo4j-core1-data:
  neo4j-core1-logs:
  neo4j-core2-data:
  neo4j-core2-logs:
  neo4j-core3-data:
  neo4j-core3-logs:
  neo4j-single-ssl-data:
  neo4j-single-ssl-logs:
  neo4j-self-signed-data:
  neo4j-self-signed-logs:

networks:
  neo4j-network:
    driver: bridge