name: dart_packstream
description: A Dart library for serializing and deserializing data using the Packstream format.
version: 0.0.2
resolution: workspace
repository: https://github.com/exaby73/dart_neo4j/tree/main/packages/dart_packstream

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
