name: dart_packstream
description: A starting point for Dart libraries or applications.
version: 0.0.1
resolution: workspace
repository: https://github.com/exaby73/dart_neo4j/tree/main/packages/dart_packstream

environment:
  sdk: ^3.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
