name: dart_neo4j_ogm_generator
description: Code generator for dart_neo4j_ogm annotations. Generates Cypher query construction methods for Neo4j OGM.
version: 0.1.0
resolution: workspace
repository: https://github.com/exaby73/dart_neo4j/tree/main/packages/dart_neo4j_ogm_generator

environment:
  sdk: ^3.7.0

dependencies:
  # Core build system dependencies
  build: ^3.1.0
  source_gen: ^3.1.0

  # Template rendering
  arcade_views: ^0.1.0

  # Analyzer for code inspection
  analyzer: ^7.7.1

  # Annotation package
  dart_neo4j_ogm: ^0.1.0

dev_dependencies:
  # Testing
  test: ^1.24.0
  build_test: ^3.0.0

  # Neo4j driver for integration tests
  dart_neo4j: ^0.1.0

  # Freezed for testing compatibility
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.0
  json_serializable: ^6.11.1

  # Build runner for development
  build_runner: ^2.4.0
