name: dart_neo4j_ogm
description: Annotations for Neo4j Object-Graph Mapping (OGM) code generation in Dart.
version: 0.2.0
resolution: workspace
repository: https://github.com/exaby73/dart_neo4j/tree/main/packages/dart_neo4j_ogm

environment:
  sdk: ^3.8.0

dev_dependencies:
  test: ^1.21.0
