name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  integration-tests:
    name: Test dart_neo4j with Neo4j containers
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dart-version: ["3.8.0"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.dart-version }}

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            **/.dart_tool
            **/pubspec.lock
          key: ${{ runner.os }}-pub-${{ hashFiles('packages/*/pubspec.yaml', 'pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dpk
        run: dart pub global activate dpk

      - name: Get dependencies
        run: dpk get

      - name: Generate SSL certificates
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents before generation:"
          ls -la
          
          echo "Generating SSL certificates..."
          chmod +x scripts/generate-ssl-certs.sh
          ./scripts/generate-ssl-certs.sh
          
          echo "Contents after generation:"
          ls -la
          
          if [ -d ssl-certs ]; then
            echo "SSL certs directory exists, checking permissions:"
            ls -ld ssl-certs/
            echo "Setting explicit permissions for CI:"
            chmod -v 755 ssl-certs
            chmod -v 644 ssl-certs/* 2>/dev/null || echo "No files to chmod in ssl-certs"
            
            echo "Final permissions after chmod:"
            ls -la ssl-certs/
            
            echo "Testing file access as current user:"
            whoami
            id
            if [ -f ssl-certs/ca-cert.pem ]; then
              echo "ca-cert.pem exists, trying to read first 3 lines:"
              head -3 ssl-certs/ca-cert.pem || echo "Failed to read ca-cert.pem"
            else
              echo "ca-cert.pem does not exist"
            fi
          else
            echo "ERROR: ssl-certs directory was not created!"
            echo "Script might have failed. Let's check the script exists:"
            ls -la scripts/
          fi

      - name: Start Neo4j containers
        run: |
          echo "Starting all Neo4j containers..."
          docker compose up -d
        env:
          COMPOSE_HTTP_TIMEOUT: 120

      - name: Verify Neo4j containers are healthy
        run: |
          echo "Checking container status..."
          docker compose ps

          # Verify basic connectivity to each instance
          echo "Testing neo4j-single connection..."
          until docker exec neo4j-single cypher-shell -u neo4j -p password 'RETURN "single" as instance' 2>/dev/null; do
            echo "Waiting for neo4j-single..."
            sleep 5
          done

          echo "Testing cluster connectivity..."
          until docker exec neo4j-core1 cypher-shell -u neo4j -p password 'RETURN "cluster ready" as status' 2>/dev/null; do
            echo "Waiting for neo4j cluster..."
            sleep 5
          done

          echo "Checking SSL container status..."
          docker logs neo4j-single-ssl --tail 10
          docker logs neo4j-self-signed --tail 10

          echo "Testing SSL container HTTP interfaces..."
          curl -f http://localhost:7478/ || echo "SSL container HTTP not ready"
          curl -f http://localhost:7479/ || echo "Self-signed container HTTP not ready"

          echo "Basic Neo4j instances are ready!"
          echo "SSL containers status checked - Dart tests will handle SSL connectivity."

      - name: Verify SSL certificates before tests
        run: |
          echo "Pre-test verification working directory: $(pwd)"
          echo "Contents of workspace root:"
          ls -la
          
          if [ ! -d ssl-certs ]; then
            echo "SSL certificates missing! Re-generating..."
            chmod +x scripts/generate-ssl-certs.sh
            ./scripts/generate-ssl-certs.sh
            chmod 755 ssl-certs
            chmod 644 ssl-certs/*
            echo "Re-generated certificates:"
            ls -la ssl-certs/
          else
            echo "SSL certificates found:"
            ls -la ssl-certs/
          fi

      - name: Run dart_neo4j integration tests
        run: |
          echo "Test step working directory: $(pwd)"
          echo "SSL_CERTS_PATH: $SSL_CERTS_PATH"
          echo "Final check - SSL certs at specified path:"
          ls -la "$SSL_CERTS_PATH" 2>/dev/null || echo "Directory STILL not found at $SSL_CERTS_PATH"
          echo "Running tests..."
          dpk run test:neo4j
        env:
          SSL_CERTS_PATH: ${{ github.workspace }}/ssl-certs

      - name: Stop Neo4j containers
        if: always()
        run: docker compose down -v
