name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  integration-tests:
    name: Test dart_neo4j with Neo4j containers
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dart-version: ["3.8.0"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.dart-version }}

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            **/.dart_tool
            **/pubspec.lock
          key: ${{ runner.os }}-pub-${{ hashFiles('packages/*/pubspec.yaml', 'pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dpk
        run: dart pub global activate dpk

      - name: Get dependencies
        run: dpk get

      - name: Start Neo4j containers
        run: |
          # Start certificate generator first and wait for certificates to be created
          docker compose up -d ssl-cert-generator
          
          # Wait for certificates to be generated
          echo "Waiting for SSL certificates to be generated..."
          for i in {1..30}; do
            if [ -f ssl-certs/ca-cert.pem ] && [ -f ssl-certs/server-cert.pem ] && [ -f ssl-certs/self-signed-cert.pem ]; then
              echo "SSL certificates found!"
              break
            fi
            echo "Waiting for certificates... ($i/30)"
            sleep 2
          done
          
          # Fix certificate permissions for the runner user
          echo "Fixing certificate permissions..."
          echo "Before fixing permissions:"
          sudo ls -la ssl-certs/ || echo "Cannot list ssl-certs directory"
          
          sudo chown -R runner:docker ssl-certs/ || sudo chown -R $USER:$USER ssl-certs/
          sudo chmod -R 755 ssl-certs/
          sudo chmod -R 644 ssl-certs/*.pem
          
          echo "After fixing permissions:"
          ls -la ssl-certs/

          echo "Starting all Neo4j containers..."
          docker compose up -d
        env:
          COMPOSE_HTTP_TIMEOUT: 120

      - name: Verify Neo4j containers are healthy
        run: |
          echo "Checking container status..."
          docker compose ps

          # Verify basic connectivity to each instance
          echo "Testing neo4j-single connection..."
          until docker exec neo4j-single cypher-shell -u neo4j -p password 'RETURN "single" as instance' 2>/dev/null; do
            echo "Waiting for neo4j-single..."
            sleep 5
          done

          echo "Testing cluster connectivity..."
          until docker exec neo4j-core1 cypher-shell -u neo4j -p password 'RETURN "cluster ready" as status' 2>/dev/null; do
            echo "Waiting for neo4j cluster..."
            sleep 5
          done

          echo "Checking SSL container status..."
          docker logs neo4j-single-ssl --tail 10
          docker logs neo4j-self-signed --tail 10

          echo "Testing SSL container HTTP interfaces..."
          curl -f http://localhost:7478/ || echo "SSL container HTTP not ready"
          curl -f http://localhost:7479/ || echo "Self-signed container HTTP not ready"

          echo "Basic Neo4j instances are ready!"
          echo "SSL containers status checked - Dart tests will handle SSL connectivity."

      - name: Debug SSL certificate paths
        run: |
          echo "GitHub workspace: ${{ github.workspace }}"
          echo "Current directory: $(pwd)"
          echo "SSL_CERTS_PATH will be: ${{ github.workspace }}/ssl-certs"
          echo "Checking if SSL certs exist at expected path:"
          ls -la ${{ github.workspace }}/ssl-certs/ || echo "SSL certs not found at workspace path"
          echo "Checking if SSL certs exist at relative path:"
          ls -la ssl-certs/ || echo "SSL certs not found at relative path"

      - name: Run dart_neo4j integration tests
        run: dpk run test:neo4j
        env:
          SSL_CERTS_PATH: ${{ github.workspace }}/ssl-certs

      - name: Stop Neo4j containers
        if: always()
        run: docker compose down -v
